# Site Settings
baseurl: "/hashtag"
title: "SociÃ©tÃ© algorithmique"

name: "SociÃ©tÃ© algorithmique"
description: Une chaire de recherche de l'institut MIAI
url: "https://github.com/gillesbastin"			

paginate: 3
paginate_path: "blog/page:num"

twitter: gillesbastin
email: gilles.bastin@iepg.fr

disqus: 
analytics:

copyright: ğŸ„¯Chaire SociÃ©tÃ© algorithmique, 2019	

# Build Settings
permalinks: pretty
